[project]
name = "simple-calculator"
version = "0.0.0"
description = "Simple calculator FastMCP server example"
requires-python = ">=3.10"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
